version: '3.8'

services:
  spring-app:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
